services:
  flask:
    build: ./backend
    container_name: backend-flask
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
    restart: on-failure
    volumes:
      - ./backend:/backend
    ports:
      - "5000:5000"
    command: python server.py
  frontend:
    build: ./frontend
    container_name: frontend
    restart: on-failure
    ports:
    - "3000:3000"